FROM ubuntu:20.04

# https://github.com/moby/moby/issues/4032#issuecomment-163689851
# https://github.com/moby/moby/issues/4032#issuecomment-192327844
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update --fix-missing && apt upgrade -y
RUN apt install -y \
    wget \
    tar \
    openjdk-11-jdk

ENV SPARK_VERSION=3.1.2
ENV HADOOP_VERSION=3.2
ENV SPARK_HOME=/root/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}

ENV SPARK_MASTER_PORT=7077
ENV SPARK_UI_PORT=8080

# Download spark binaries
RUN cd /tmp && \
    wget https://apache.mirrors.nublue.co.uk/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

# Install spark binaries to home directory (matching flintrock)
RUN cd ~ && \
    tar -vxf /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    rm /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
