FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update --fix-missing && apt upgrade -y
RUN apt install -y \
    wget \
    tar \
    openjdk-11-jre

ENV SPARK_VERSION=3.1.1
ENV HADOOP_VERSION=3.2

ENV SPARK_MASTER_PORT=7077
ENV SPARK_UI_PORT=8080

RUN \
    cd /tmp && \
    wget -q https://apache.mirrors.nublue.co.uk/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    tar -vxf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /usr/share/spark && \
    rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
